### ISSUE TITLE
Invalid number of conflict markers

### ISSUE THREAD

**Issue by achikin** [mkchoi212/fac#12]
I have created a repo to test fac. I created a sample file, then I created two branches and made two different changes in that file, than I merged those branches into master, got a conflict and tried to run `fac` to fix it.
Here is the terminal output(besides the error itself please mention that fac does not add \n after the error message, which makes bash print status message on the same line after fac exit.
```
~/src/factest (master|MERGING) → ls
somefile
~/src/factest (master|MERGING) → cat somefile
<<<<<<< HEAD
aa
||||||| merged common ancestors
aaaa
=======
dddd
>>>>>>> second
bbbb
cccc
~/src/factest (master|MERGING) → fac
Invalid number of remaining conflict markers~/src/factest (master|MERGING) →
```
```
→ git --version
git version 2.15.1
```

**Comment by mkchoi212** [comment]
Hmmm I'll look in to it. Thanks

**Comment by mkchoi212** [comment]
Did `git` put in the line
```
||||||| merged common ancestors
```
@achikin

**Comment by mkchoi212** [comment]
@achikin  For now, with e493f7172e9f24572440db3d6e9b61efc04c3160, fac prints a warning message for diff3 conflict markers instead of printing an irrelevant error message.

**Comment by mkchoi212** [comment]
@achikin I have not been able to get around it this due to school :( I will start looking at it in couple of weeks when school is over!

**Comment by mkchoi212** [comment]
Support for diff3 has been added with the newest v.1.1.0 release! 

https://github.com/mkchoi212/fac/commit/ce0a0434a425e6b16e6055909e10696fc2ad8081
