### ISSUE TITLE
Console color doesn't work on windows

### ISSUE THREAD

**Issue by itsnotvalid** [mkchoi212/fac#13]
Trying this with a win10 machine, and it only prints the \x1b[32;1m version on cmd.exe shell (works with Powershell though).
e.g.
`[32;1mNo conflicts detected 🎉[0m`

Suggestion would be using some other packages like https://github.com/sirupsen/logrus, https://github.com/mattn/go-colorable or https://github.com/fatih/color.

**Comment by mkchoi212** [comment]
@itsnotvalid Thank you! I'll make sure to check those packages out and fix this asap.

**Comment by mkchoi212** [comment]
@itsnotvalid Are the colors displaying correctly when you run `fac` and actually see the code where the conflicts are?

**Comment by mkchoi212** [comment]
Closing this issue because it has to do with `cmd.exe` and Windows supports bash.

However, if someone figures out how to support colors for the Windows Command Line, a PR would be much appreciated :D
