### ISSUE TITLE
Long filenames hide the current file marker

### ISSUE THREAD

**Issue by hkdobrev** [mkchoi212/fac#14]
Long filenames could hide the marker of the current file. It could be moved to the left and/or different colour for the active file could be used.

Since filenames are truncated in the sidebar, the full path and filename of the active file could be shown at the top of the main window.

**Comment by mkchoi212** [comment]
I like the idea of having the indicator at the left of the active file.

**Comment by mkchoi212** [comment]
Fixed with a6f86b929de1f0bb360adc47bff7a49f67baefd2
