### ISSUE TITLE
Persist view option

### ISSUE THREAD

**Issue by hkdobrev** [mkchoi212/fac#15]
If I've opened `fac` and used `v` to change the view setting, I would expect this configuration to persist between sessions. It doesn't do that, though.

**Comment by mkchoi212** [comment]
I find myself using the `v` shortcut quite frequently depending on the kind of code I am looking at.

But we could look into create a `.config` file to persist view + keyboard shortcut (configurations)!

**Comment by mkchoi212** [comment]
This will probably be to much of an overkill with the implementation of https://github.com/mkchoi212/fac/issues/22. And considering that the view orientation is changed frequently and is easy to do so, I'm closing the issue.

If you have comments/thoughts, please let me know though 😄
