### ISSUE TITLE
Feature request: Key input without pressing enter

### ISSUE THREAD

**Issue by ipwnponies** [mkchoi212/fac#22]
The key controls are single characters. It would be nice if actions immediately triggered after pressing the keys, without hitting enter key.

**Comment by mkchoi212** [comment]
Right now, you can input any keys that are related to movement `n` times in order to execute it `n` times. So `www` would show 3 more lines on the top.

Regarding the actions being triggered immediately, I think it should remain as it is. It just acts as a safeguard against mistakes. What do you think?

**Comment by ipwnponies** [comment]
This still requires `www<CR>`. It would be more intuitive and mimic vim's normal mode/gamer's wasd to execute upon keypress.

I can suggest two things (and/or):
* Modes ala vim. Normal mode (what I'm requesting) and command mode (to provide more flexibility for less used commands, maybe `reset/collapse`)
* Configuration option to set this mode, allows for safer default behaviour without limiting "power users"

**Comment by ipwnponies** [comment]
@mkchoi212 I can take a stab at implementing this, if you think it's low priority but possibly useful. I've never written go before but this looks like a small fix (short circuiting the <CR> if config option is set). Let me know what direction you want to take this.

**Comment by mkchoi212** [comment]
The fix wouldn't be that hard but I personally want for the user to press enter before confirming their actions as a safety measure. Because for actions like selecting a particular version of the code, it's almost irreversible unless you do a `git reset`. What do you think about this?

**Comment by ipwnponies** [comment]
I'm beginning to understand your hesitation. In my workflow, if I end up incorrectly resolving the merge conflict, I will git checkout -m <FILE> to reset merge conflict on the file. But I can see how for large files changes with many conflicts, this can problematic.

The quickest change would be a config that allows me to override behaviour and accept the consequences. Since it's not default, there's an understanding of this risk and power users will not be restricted by these safeties.

A more complete and complex feature implementation would be to white/blacklist certain mappings. I'm thinking that blacklisting is probably the way to go, since the only destructive mapping atm is to choose `yours` (a) or `theirs` (d). These can have additional confirmation prompts. With this approach, you could do away with the config and make this behaviour the same for everyone. You'd need to consider how this impacts the UX and flow w.r.t. to other features or plans you had in mind with this project.

**Comment by mkchoi212** [comment]
Gotcha. I'll give it some thought!

**Comment by MatiasConTilde** [comment]
What about immediately moving around (w, s, j, k, n, p), but having to confirm for irreversible actions (a, d)?

**Comment by mkchoi212** [comment]
@MatiasConTilde Yeah I had the same thought but I think it could be slightly counter-intuitive.

**Comment by mkchoi212** [comment]
@MatiasConTilde @ipwnponies I just implemented a version of fac that parses inputs without having to press `enter`. You can check it out at https://github.com/mkchoi212/fac/tree/no-enter. 

To try it out, clone the repo and `go install`. I would love your feedback on it 😃

**Comment by ipwnponies** [comment]
@mkchoi212 I've installed this and will try it out over the next few weeks.

**Comment by MatiasConTilde** [comment]
Is there some easy and quick way to create conflicts for testing? I usually only have some veeryy rarely.

**Comment by ipwnponies** [comment]
@MatiasConTilde Create two branches from the same start commit. Make changes to the same, existing file on same lines (config files such as requirements.txt, setup.py, tox.ini in python projects are great candidates, plus commonly where one might encounter real-world conflicts). 

From here, it's trivial to enter conflict state by merging one into the other. To undo merge conflict resolution to rerun `fac`, use `git checkout -m <FILE>`. Use `git merge --abort` to exit git merge state altogether. Don't commit/complete the merge and these two branches can be used indefinitely to quickly repro confict state reliably.

**Comment by hkdobrev** [comment]
@mkchoi212 Just to mention Git itself does not wait for Enter in interactive inputs like `git add --patch` or `git add --interactive`. In `--patch` interfaces (add, checkout, reset, stash) - it just has a key to return to the previous chunk in the file using <kbd>K</kbd>.

I think this is a better way to go and it's faster to work with.

**Comment by mkchoi212** [comment]
@hkdobrev What about `y` or `n` in `git add -p`? They definitely wait for `Enter`.

**Comment by hkdobrev** [comment]
OK, Git actually waits for Enter, not sure what got into me. I actually tried it a few times to catch myself that I press Enter. It's muscle memory now. Sorry for the noise!

**Comment by mkchoi212** [comment]
@hkdobrev @ipwnponies Verdict??

**Comment by ipwnponies** [comment]
@mkchoi212 I'm liking the responsiveness with this change. It's a more fluid experience, matches closely with interactivity of`git --patch` flows and `vim`.

Just a note on my workflow and how I've been using `fac`, it's primarily for viewing diff and navigation, I haven't been using the 'resolve using yours/theirs' extensively.

**Comment by mkchoi212** [comment]
Closing this issue. This feature will most likely be part of https://github.com/mkchoi212/fac/issues/29

**Comment by alok** [comment]
I'd love to see this added since #29 seems to be working fine.

**Comment by mkchoi212** [comment]
With https://github.com/mkchoi212/fac/commit/8e39330e01eab8d14528a39d5a2d18d33bd5a783, you can now define `cont_eval` key in `.fac.yml` to toggle the behavior of not having to press enter for evaluation.

Please refer to https://github.com/mkchoi212/fac/blob/master/binding/README.md for more detail
