### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Tchoupinax** [mkchoi212/fac#23]
Hello,

Yesterday i installed your software on MacOS and it worked well, but today i have this error when i tried to execute the binary : 
`bash: /home/linuxbrew/.linuxbrew/bin/fac: cannot execute binary file: Exec format error`

What is the problem ?
My uname is : 
`Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

I did not have yet a conflict, but next time i will try FAC ! :)
Thank you for your work.

**Comment by mkchoi212** [comment]
I have never used linuxbrew so I'm not sure but I think it may have downloaded the wrong binary file.

Try going to https://github.com/mkchoi212/fac/releases and manually downloading the appropriate distribution! Thanks 🙂
