### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Aethelflaed** [mkchoi212/fac#25]
Hi,

Thanks for the project, looks really nice and I'd really want to try it! But for now, I can't get to build it...

I barely now anything about go, so if you need more information just tell me what you need:

go version go1.8.3 gccgo (GCC) 7.2.1 20171224 linux/amd64

stderr: https://gist.github.com/Aethelflaed/d813e7bd535ea27fe460c4f6fa4a9567

**Comment by mkchoi212** [comment]
Hi and thank you!

Are your GOPATH, GOROOT set up correctly?

**Comment by Aethelflaed** [comment]
Thanks for the (very) quick reply, I'm rather long on my side...

GOPATH and GOROOT are not set, and I just tried googling it to see what it is, and AFAIK is should be able to find ~/go by itself...

However, trying `GOROOT=~/go go get github.com/mkchoi212/fac` does not show the same errors...

**Comment by mkchoi212** [comment]
Just to clarify, are you saying that you get the error messages in https://gist.github.com/Aethelflaed/d813e7bd535ea27fe460c4f6fa4a9567 when you just run `go get github.com/mkchoi212/fac`?

**Comment by Aethelflaed** [comment]
Yup, that's exactly what I get
