### ISSUE TITLE
Paths don't resolve correctly when starting fac from sub directory

### ISSUE THREAD

**Issue by gruhn** [mkchoi212/fac#26]
`fac` seems to have trouble resolving paths when I start it from anything other than the repositories root directory. In the example below, `fac-test` is the repository root and `file.md` is a conflicted file in the `sub-dir` folder. 

![bildschirmfoto vom 2018-01-28 15-21-04](https://user-images.githubusercontent.com/26570572/35483191-823977fe-043f-11e8-98bb-8eb0b0da10fa.png)

Anyway, thanks for this tool. I'm looking forward to upcoming features :grin:

**Comment by mkchoi212** [comment]
@gruhn Thanks for opening the issue. I'll take a look at it ASAP!

**Comment by mkchoi212** [comment]
This has been fixed with the latest v1.1.0 release.
