### ISSUE TITLE
Remove emojis from output messages

### ISSUE THREAD

**Issue by lenormf** [mkchoi212/fac#40]
Hi,

It'd be nice to remove emojis from messages, as they are not supported by all terminals and just litter the terminal.

**Comment by mkchoi212** [comment]
Ah, that is true. What do you think about adding support in `.fac.yml` for something like `disable_emoji: true`

**Comment by lenormf** [comment]
I think they should be disabled by default, since they don't give any additional information than what's already hinted at by colors.
