### ISSUE TITLE
How to show context of 4 lines by default during merges?

### ISSUE THREAD

**Issue by shadyabhi** [mkchoi212/fac#44]
By default, it's not showing any lines unless I press "w" or "s"

**Comment by mkchoi212** [comment]
That's not a feature yet but it would be a great addition to [.fac.yml](https://github.com/mkchoi212/fac/blob/master/binding/README.md)! PRs are welcome 😄

**Comment by shadyabhi** [comment]
@mkchoi212 Thanks for replying. Please check https://github.com/mkchoi212/fac/pull/45

**Comment by mkchoi212** [comment]
Closed with https://github.com/mkchoi212/fac/commit/024a9a92b33c2ca19953ee0a21501323038ceef1
