### ISSUE TITLE
Long list of conflicts hide the help

### ISSUE THREAD

**Issue by hkdobrev** [mkchoi212/fac#5]
When you have a long list of conflicts, the help text with the keyboard shortcuts is hidden.

Git has often this notion of selecting <kbd>?</kbd> for showing help with an explanation for the choices.

Perhaps you could mimic what Git does in interactive tools on the command line and list all the possible keys on the command prompt with a question mark `?` at the end. If the question mark is selected it would print the keys meaning somewhere.

**Comment by mkchoi212** [comment]
For now, the help text is not displayed until the user types `?` or `h`.

But you are right but the shortcuts being hidden with a long list of conflicts. To solve this, I was thinking about dedicating a separate panel that would go on top of the conflict list panel. 

I thought about listing all the commands on the prompt but as an avid `git add -p` user, I never look at all the options and have never found them to be useful.

**Comment by hkdobrev** [comment]
> I thought about listing all the commands on the prompt but as an avid `git add -p` user, I never look at all the options and have never found them to be useful.

It's the same for me until you show it to someone else who sees it for the first time or use it in a pairing session where you use a letter which the others don't know about. IMHO it's always useful to list them on the command prompt with a question mark for more info.

**Comment by mkchoi212** [comment]
Good point. So would `[w,a,s,d,?] >> ` be ok?

**Comment by mkchoi212** [comment]
For now, I've placed just a `?` at the end of prompt to inform people of the command. See 58415774022b3476505fd20dc66f21ecd71374e5

**Comment by alok** [comment]
@mkchoi212 Do you actually use the `git add -p` prompt? I've always found it hideous and use `tig`'s much nicer interface or occassionally (vi)magit.

**Comment by mkchoi212** [comment]
@alok Yes. I've never used `tig` though. I will check that out.
