### ISSUE TITLE
Unclear how to actually resolve the conflict

### ISSUE THREAD

**Issue by SirCmpwn** [mkchoi212/fac#6]
The controls are all about navigating... nothing about actually fixing the conflict.

**Comment by mkchoi212** [comment]
A and d “selects” one of the two conflicts. I should have chosen a better word for them.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mkchoi212** [comment]
What do you think of using `1` or `2` to select the conflicts? @SirCmpwn

**Comment by SirCmpwn** [comment]
Hmm. Conflicts that are solved with an ours or theirs approach is generally pretty rare (I'd also note that "ours" and "theirs" is the terminology you should use here). Most of the time I have to manually tweak the final result. Most conflict resolution tools have three screens - ours, theirs, and final, and lets you edit the third.

**Comment by mkchoi212** [comment]
I agree. So I was thinking of adding an `e` for `[e]dit` option. But instead of displaying a third panel for it, I would launch the user's default editor.

**Comment by SirCmpwn** [comment]
I can resolve conflicts in vim without your tool.

**Comment by mkchoi212** [comment]
Well I guess the problem has been solved then!

**Comment by SirCmpwn** [comment]
That's not what I mean. I mean if you're just going to launch the user's editor to resolve conflicts with why wouldn't they just skip the middleman?

**Comment by mkchoi212** [comment]
Fac could open up vim without all the nasty markers. The user could choose one of the two choices before fac opens up the editor.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
